postgres:
    image: postgres:15.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cdp
    volumes:
       - ./data:/var/lib/postgresql/data
